Portfolio accessibility
Unleashedicon/personal-portfolio-project pull request #8
Opened 2023-02-01 17:07 UTC by Unleashedicon

### Report on accessibility

- **Page titles**- No issue found

- **Image text alternatives ("alt text")** -https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/index.html#L67-L68
 https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/index.html#L180
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/index.html#L190
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/index.html#L190

- **Text headings**- No issue found

- **Color contrast** - https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/styles.css#L431
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/styles.css#L539
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/styles.css#L621
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/styles.css#L680
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/styles.css#L770
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/styles.css#L1148
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/styles.css#L1250
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/styles.css#L1541
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/styles.css#L1566

**Resize** - No issue found

**Interaction** - Form labels and error
https://github.com/Unleashedicon/personal-portfolio-project/blob/portfolio-accessibility/index.html#L217-L219

**Moving content**- No issue found

**Multimedia**- No issue found

**The basic structure of the page**- No issue found

2023-02-01 17:20 UTC, amejid reviewed
Hi @Unleashedicon, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that does not have commits from your pair-programming partner. The project is a pair-programming activity.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-02 10:19 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @team 👋

Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! 
**_However, I did notice a few areas where some additional changes would further enhance the quality of the portfolio. But you are almost there!_** 💪 🏁 **_I wish you success 🥇_**

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Well done so far following the given Figma design
- ✅ Great job with CSS
- ✅ Descriptive PR and README file
- ✅ Well done with PR summary
- ✅ Correct Linters

However, there is always room for improvement.

## Required Changes 🛑

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_

- [ ] Please consider improving the page title for your project. Good page titles are important to help people to move between pages open in their browser. The first thing screen readers say when the user goes to a different web page is the page title 🚧. For example:
- **_Poor titles:_**
    - Microverse project | Your portfolio.
    - Portifolio project
- **_Better page titles_**:
    - Mark's portifolio
    - Mark full-stack webdeveloper
- [ ] I noticed that you are using `<h1>` for your `logo` on `line 15`. If you notice most of the webpages, the logo is served as a link to `home page`. The idea here is to do the same. What do you think? 🤔🎯. Also in this way, you can use `<h1>` to highlight the most important content of your portfolio. Please consider using an `<a>` tag for your logo. This can b simply done in 2 steps (You can use your own styles)
    - _By changing `<h1>` to `<a>`_
    - _Add style `text-transform: none` to `<a>` tag_


_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 10:19 UTC, KanzaTahreem commented on index.html
> +            <img src="images/Img Placeholder.png" class="image2" alt="">
- [ ] Great job applying those accessibility best practices to your project! 💯 However, I suggest you revert this change with a better `alt` text. For example, it can be `project card`. Text alternatives convey the purpose of an image. These are used by people who do not see the image. I think it would be a great idea to provide `alt` attribute here instead of keeping it empty so that screen readers can know about the project image 🤓 🔧

2023-02-02 10:19 UTC, KanzaTahreem commented on index.html
>      <h1 class="greeting">Hey There.<br> I'm Kelvin</h1>
- [ ] I noticed that you are using multiple `<h1>` tag throughout the portfolio. Ideally, you would want to have only one `<h1>` element for each page, this tag is reserved for the title that describes better the content of the page. It serves as an index for search engines to find your page, so please consider changing this! 🤓 🔧. Also, the heading levels should have a meaningful hierarchy, e.g.:
    - _Heading Level 1 `<h1>`_
      - _Heading Level 2 `<h2>`_
        - _Heading Level 3 `<h3>`_
      - _Heading Level 2 `<h2>`_
        - _Heading Level 3 `<h3>`_
            - _Heading Level 4 `<h4>`_
      - _Heading Level 2 `<h2>`_
 
- [ ] Right now, this is how your page is structured 🔽
  ![image](https://user-images.githubusercontent.com/106119105/216285821-39c56f16-23a5-4269-b601-c54240303076.png)

2023-02-04 10:59 UTC, merged